version: '3.3'
services:
  
  frontend-pdb03:
    container_name: frontend-pdb03
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=local
      - ES_HOST=es01-pdb03
      - PORT=3000

  es01-pdb03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es01-pdb03
    environment:
      - node.name=es01-pdb03
      - cluster.name=es-pdb03
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - http.cors.allow-headers=Content-Type,Access-Control-Allow-Headers,Authorization,X-Requested-With
      - discovery.seed_hosts=es02-pdb03
      - cluster.initial_master_nodes=es01-pdb03,es02-pdb03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01-pdb03:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02-pdb03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: es02-pdb03
    environment:
      - node.name=es02-pdb03
      - cluster.name=es-pdb03
      - discovery.seed_hosts=es01-pdb03
      - cluster.initial_master_nodes=es01-pdb03,es02-pdb03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02-pdb03:/usr/share/elasticsearch/data
    networks:
      - elastic
  
volumes:
  data01-pdb03:
    driver: local
  data02-pdb03:
    driver: local
  
networks:
  elastic:
    driver: bridge
